### PR TITLE
Events page

### LINKED ISSUE #52: Events page
We need to add an events page for hackathons that will allow the editing of the event title, link and text.

### PR DESCRIPTION
**Pull request by panjenny0**
closes #52 
Screen-Recording-2020-10-19-at-1
Screen Shot 2020-10-19 at 12 24 44 AM

### CODE REVIEW

**Comment by panjenny0** [comment]
> I was linked to this article at my coop when I didn't use braces in an if statement https://dwheeler.com/essays/apple-goto-fail.html (3.3)

ty @ianmah

**Review by ianmah — APPROVED** [review]
Ooh nice a real date picker LOL I made my own in #51 but I will wait for u to merge and use the one you added in my PR.

Nit: use lowerCamelCase for DateTimePicker to be consistent?

**Comment by Ciuffi** [comment]
@kozr could you have a look and make sure it has all the features needed by your team? If so, please approve it!

**Comment by Ciuffi** [comment]
@kozr specifically make sure we're using the correct timestamps and that all the fields are there

**Review by Ciuffi — APPROVED** [review]
Great job! Thanks for crunching this out. Let nick approve this before merging though.

**Comment by panjenny0** [comment]
> Ooh nice a real date picker LOL I made my own in #51 but I will wait for u to merge and use the one you added in my PR.
> 
> Nit: use lowerCamelCase for DateTimePicker to be consistent?
@ianmah Oh yours is pretty creative! I renamed the file 👍

**Review by kozr — APPROVED** [review]
Awesome! This would work for now, but we would eventually need to store an image for the event similar to how http://nwplus.io/ works. Might also need to update https://github.com/nwplus/database-schemas/blob/master/nw-firestore-schema.ts too.

**Pull request merged**
